### ISSUE TITLE
How can I add more metadata to spans?

### ISSUE THREAD

**Issue by sergimola** [nioc/node-red-contrib-opentelemetry#9]
It would be nice to be able to add more metadata to the spans.
Is there a way to do that now?

**Comment by nioc** [comment]
Can you be more specific? Which data?

**Comment by sergimola** [comment]
Literally anything I want.
I use Node-RED with HomeAssistant and your node is a great addition. Now I see for instance when an event is triggered because a sensor state changed or I see when I invoke an action on an entity in HomeAssistant.
Only that is really good, but if I could be able to add additional attributes to my spans to have more context of what happened (e.g. what is the data coming in the event, the data used to invoked that action, etc.) would be incredibly much more valuable.

**Comment by nioc** [comment]
I understand that you'd like to be able to indicate to the otel node a JSONata list of attributes that would be added to the span, or something like this?

This attribute have to be unique for the entire Node-RED instance, so may be not very effective as each node has his own field (`topic`, `payload `for the more commons attributes).

**Comment by sergimola** [comment]
The idea is to be able to add manual instrumentation, which would mean
being able to create spans at any point in time.
Nevertheless, your automatic instrumentation could still be extended with
more semantic conventions and maybe that would be enough.

What I mean is.. If you establish semantic conventions depending on the
node type then you would have much more useful information in the spans.
Those semantic conventions could be probably configurable but also have
some by default for the core nodes (switch, change, etc.).

For instance, in a switch node, it'd be great to know which were the
matching conditions and probably also know the configuration of the switch
node.

**Comment by nioc** [comment]
I think the first idea:
> to be able to add manual instrumentation, which would mean
being able to create spans at any point in time

which can be resolve by adding a new `otel-span` node type with payload input is easier and less impacting.

Does this suit you?

**Comment by sergimola** [comment]
> I think the first idea:
> 
> > to be able to add manual instrumentation, which would mean
> > being able to create spans at any point in time
> 
> which can be resolve by adding a new `otel-span` node type with payload input is easier and less impacting.
> 
> Does this suit you?

How would it work? With spans you need to specify when they start and when they end and you want to capture something happening in between.
Would it be possible to have only one node or there should be an `otel-start-span` and an `otel-end-span` ?

**Comment by nioc** [comment]
The one node idea was to trace additional information in one span.
But may be, using 2 nodes (one starts the span, the other ends it) is the way to handle it.
I do not have time right now for working on this subject right now but I keep it opened.

**Comment by nioc** [comment]
Hello @sergimola, thinking about adding a [span attribute](https://opentelemetry.io/docs/concepts/signals/traces/#attributes) which, following [guidelines](https://opentelemetry.io/docs/specs/otel/common/#attribute), could be a new key `node_red.additional_info` with a JSON stringifyed of a special message attribute `msg.otelAdditionalInfo` which you can set in a function node, it should output something like this:
``` jsonc
  "attributes": {
    "node_red.additional_info": "{payload: \"mypayload\", topic: \"mytopic\"}",
    // existing attributes
    "node_red.msg.id": "",
    "node_red.flow.id": "",
    "node_red.node.id": "",
    "node_red.node.type": "",
    "node_red.node.name": "",
    // ...
  }
```

Let me know if it meets your needs.

**Comment by sergimola** [comment]
Having it as a string wouldn't be that helpful because that would make things harder for processing that data later.
Couldn't they be added as individual attributes?
```json
"attributes": {
    // existing attributes
    "node_red.msg.id": "",
    "node_red.flow.id": "",
    "node_red.node.id": "",
    "node_red.node.type": "",
    "node_red.node.name": "",
    // new attributes
    "node_red.msg.payload":"mypayload", --> the value of this could be a complex object that should be added as an object and not a string
    "node_red.msg.topic":"mytopic"
  }
```

Semantic Conventions (and Autoinstrumentation, more one that later) would work like a charm here.
You could actually introduce that without even having to write that `msg.otelAdditionalInfo`. You could decide to always (maybe make it configurable, being able to filter it out or having to turn it on on purpose) add those two attributes because those are two standard things for a message in Node-RED.

Having the above implemented would be valuable for my use case. It wouldn't be exactly what I need, but it would add quite some value on top of what the plugin already provides.

**Some more thoughts about Autoinstrumentation....**
Some weeks ago I forked the repo and played a bit with the idea of Autoinstrumentation. The idea would be to make the functionality extendable with Autoinstrumentation that could be defined by the user in a new `Autoinstrumentation` Node. In the configuration of that `Autoinstrumentation` Node one would define:
- 1 or more Node types
- 1 or more attributes (key-value pairs)

What that would mean is that every time a new span is started for a Node type defined in some `Autoinstrumentation` Node, you would add a span attribute for each key-value pair. A key-value pair could be something like.. 

| key | value |
|---|---|
| `home_assitant.action.name`       | `{{msg.payload.action}}`  --> (the value here should be any possible kind of value: number, text, json, jsonata, etc.)
| `home_assitant.action.targets` | `{{msg.payload.target.entity_id}}` |

So, imagine the key-value pair above is configured for Node type `node-red-contrib-home-assistant-websocket:api-call-service`, every time that node was used, the Span created for that Node would contain the following attributes:

```json
 "attributes": {
    // existing attributes
    "node_red.msg.id": "",
    "node_red.flow.id": "",
    "node_red.node.id": "",
    "node_red.node.type": "",
    "node_red.node.name": "",
    // new attributes from autoinstrumentation
    "home_assitant.action.name": "lights.toggle"
    "home_assitant.action.targets": ["target_1", "target_2"]
  }
```

Here's a screenshot of a kind of Node I am using as an example in case it helps understand the proposal.
![image](https://github.com/user-attachments/assets/6883bba1-0cbd-440b-a814-385f3f7baa45)


I could do some early testing on this feature if you decide to implement it. Probably I could even contribute with some parts of the implementation (the whole thing about creating a new Node-RED node with the HTML and handling of settings was a bit too much for me).

**Comment by nioc** [comment]
I think object is not a valid attribute value, from the [docs](https://opentelemetry.io/docs/specs/otel/common/#attribute) :

> - The attribute value is either:
> 
>    - A primitive type: string, boolean, double precision floating point (IEEE 754-1985) or signed 64 bit integer.
>    - An array of primitive type values. The array MUST be homogeneous, i.e., it MUST NOT contain values of different types.
>
> For protocols that do not natively support non-string values, non-string values SHOULD be represented as JSON-encoded strings.

That's why I proposed a JSON stringifyed value.

Your auto-instrumentation concept is interesting, it could be implemented into the OTEL node as a configuration of list of Node-RED msg attributes -> OTEL span attribute keys mappings in [JSONata](https://try.jsonata.org/), for example:

With the following msg:
``` json
{
  "msg": {
    "payload": {
      "action": "homeassistant.turn_on",
      "targets": {
        "floor_id": ["first_floor"],
        "area_id": ["kitchen"]
      }
    }
  }
}
```
You could set the following mapping config:

| OTEL span attribute name      | Type    | Value                           | Example                                    |
|-------------------------------|---------|---------------------------------|--------------------------------------------|
| `home_assistant.action.name`    | JSONata | `$.msg.payload.action`            | `"homeassistant.turn_on"`                    |
| `home_assistant.action.targets` | JSONata | `$.msg.payload.targets.entity_id` | `[ "light.kitchen", "switch.garage_light" ]` |

Obviously, this config should be shared in the whole Node-RED instance.

And according to my first point, we have to check if the JSONata result type (string, bool, number or array, other types should be JSON stringifyed.

**Comment by nioc** [comment]
I've made a first try on the dedicated branch (for now conf is hard coded) but I have 2 problems:
- first, I loose the first span, I have to look why...
  - before (7 spans): 
![image](https://github.com/user-attachments/assets/d2e97be8-d80e-4901-bf86-4c5a1ce3d6b8)
  - after (only 6 spans): ![image](https://github.com/user-attachments/assets/bd43e8f6-4177-4a80-b22d-1cb67b521bc5)
- and JSONata require an asynchronous execution, this involves making functions asynchronous which is not a good things for traces ordering 😞

This is my test flow:
``` json
[
    {
        "id": "9b4dda11a6577f4a",
        "type": "tab",
        "label": "Flux 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "42c6b509ada6c378",
        "type": "OpenTelemetry",
        "z": "9b4dda11a6577f4a",
        "name": "OTEL",
        "url": "http://jaeger:4318/v1/traces",
        "serviceName": "Node-RED",
        "protocol": "http",
        "rootPrefix": "Message ",
        "timeout": "1",
        "ignoredTypes": "",
        "propagateHeadersTypes": "",
        "isLogging": false,
        "x": 510,
        "y": 140,
        "wires": []
    },
    {
        "id": "483c3d00ebb0e9e7",
        "type": "inject",
        "z": "9b4dda11a6577f4a",
        "name": "",
        "props": [
            {
                "p": "ts",
                "v": "",
                "vt": "date"
            },
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "[{\"action\":\"1\",\"targets\":{\"floor_id\":[\"first_floor\"],\"area_id\":[\"kitchen\"]}},{\"action\":\"2\",\"targets\":{\"floor_id\":[\"first_floor\"],\"area_id\":[\"kitchen\"]}}]",
        "payloadType": "json",
        "x": 310,
        "y": 280,
        "wires": [
            [
                "69386cb44dc88140"
            ]
        ]
    },
    {
        "id": "f49a277553fa70b7",
        "type": "debug",
        "z": "9b4dda11a6577f4a",
        "name": "debug 1",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 860,
        "y": 280,
        "wires": []
    },
    {
        "id": "e94e1af622e2ecd0",
        "type": "function",
        "z": "9b4dda11a6577f4a",
        "name": "myFunction",
        "func": "\nreturn msg;",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 670,
        "y": 280,
        "wires": [
            [
                "f49a277553fa70b7"
            ]
        ]
    },
    {
        "id": "69386cb44dc88140",
        "type": "split",
        "z": "9b4dda11a6577f4a",
        "name": "",
        "splt": "\\n",
        "spltType": "str",
        "arraySplt": 1,
        "arraySpltType": "len",
        "stream": false,
        "addname": "",
        "property": "payload",
        "x": 510,
        "y": 280,
        "wires": [
            [
                "e94e1af622e2ecd0"
            ]
        ]
    }
]
```

**Comment by nioc** [comment]
Hello @sergimola, I resolved both issues by switching from JSONata to JMESPath.
Here is a 1.5 beta, can you test it (remove the `.txt` extension, Github won't let me upload it otherwise)?
[node-red-contrib-opentelemetry-1.5.0-beta.1.tgz](https://github.com/user-attachments/files/18323717/node-red-contrib-opentelemetry-1.5.0-beta.1.tgz.txt)

**Comment by nioc** [comment]
An example of node config:
![image](https://github.com/user-attachments/assets/0768599e-f67a-4259-b285-ed876fdb949f)

And, oh yes, I added a flow filter 😉

**Comment by sergimola** [comment]
Wow, I just tried it and it is amazing!
There are a few things to check but I understand this is just an early release, right?
I am also facing the missing spans issue.

And as an improvement, to make it really useful, we need another filter in the config. We need to be able to associate that mapping to a Node type (or list of types). Otherwise the attribute is added to all the nodes, which makes no sense.
In this case, for instance, I expect it to appear only in the `api-call-service` node, where it is relevant.
![image](https://github.com/user-attachments/assets/515bbe62-6a2f-4900-a023-5ecdef113b30)


Let me share the kind of things I will be able to do now with this new addition. (this is just a quick visualization I made to show something). I will be able to track with which devices I interact the most or at what time of the day, etc.
![image](https://github.com/user-attachments/assets/2298a29b-121d-4efe-b59d-d076d9210f69)

**Comment by nioc** [comment]
Yes this pre release is a beta to confirm that I am in the good direction regarding your needs.

Adding `node type` in config/filter should be ok. Those wishing to avoid headaches can leave the node type empty (like the flow id field). Note that you may also filter on your Elastic query 😉

I will also add a debug in next beta to investigate spans loss, I suspect that some data types are not valid, for now I just [skip](https://github.com/nioc/node-red-contrib-opentelemetry/blob/a8b51c579d78d30b15e5abf404d5efd1fbb844a7/lib/opentelemetry-node.js#L97-L104) `object` type

Can you provide me a simulated flow export (with a payload in an inject) that reproduces this behavior?

**Comment by sergimola** [comment]
> @sergimola here is a beta 2 with:
> 
> * node type filter,
> * better rule for attribute value,
> * debug log for local attributes 😃
> 
> [node-red-contrib-opentelemetry-1.5.0-beta.2.tgz.txt](https://github.com/user-attachments/files/18350931/node-red-contrib-opentelemetry-1.5.0-beta.2.tgz.txt)
> 
> If it is ok for you (your needs are fulfilled and with this new beta version you have the same spans number as with 1.4.0), I will merge.
> 
> Otherwise, please provide an example flow for reproduce the span loss, thanks.

I've been able to try it now and the node type filter is amazing. Now it fulfills exactly what I needed! 🚀 
Congrats for the new functionality, it truly is helpful.

About the "missing spans", I've seen what's the problem. They are actually not lost, but somehow the initial span always gets outdated and then after 20s (as per config) it is closed and pushed to the OTEL Collector. I am not sure that was the behaviour before, maybe I didn't notice it.

**Comment by sergimola** [comment]
After playing a bit more with it, I have a use case that can't be fulfilled with the new feature and I wanted to know your opinion about it.

Without looking at the code, I am assuming you are adding the attribute spans when the span is created/started. But, what if the data I need to be put as an attribute is actually generated after the node has finished processing the message?

This is an example. I am receiving an event from Home Assistant and the node sets in the payload (or wherever you configure) the kind of event it was, the data it contained, etc. That information is super valuable information to understand what happened in the system, but it's not available at the initial hook when you create the span (again, this is my assumption without looking at the new code you added).
![image](https://github.com/user-attachments/assets/2adfc375-dc12-4fea-a26f-6f29a0873cb3)


Would it make sense to add the attributes at the latest hook possible (`onComplete`?) just before ending the span? Should that be configurable in each mapping? (too much configuration?)

You can simulate that with this simple flow. The `inject` node sets `msg.payload.dummy` to `1234` and the `function` changes it to `hello`. The span for the `function` will show `dummy=1234` instead of `dummy=hello`.

```json
[
    {
        "id": "8f6bb4b5d7570d82",
        "type": "inject",
        "z": "8cf883f1bd557579",
        "name": "",
        "props": [
            {
                "p": "payload.dummy",
                "v": "1234",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 110,
        "y": 540,
        "wires": [
            [
                "cc08e9319231e7af"
            ]
        ]
    },
    {
        "id": "cc08e9319231e7af",
        "type": "function",
        "z": "8cf883f1bd557579",
        "name": "function 3",
        "func": "msg.payload.dummy = \"hello\"\nreturn msg;",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 280,
        "y": 540,
        "wires": [
            []
        ]
    }
]
```

**Comment by nioc** [comment]
That was on purpose 😉 as I often need the input value. But the output value should be interesting too.
So I'm ok to add a select field on HTML to choose if the attribute value should be set as input (on span creation) or ouput (on span ending) of node processing.
I have to check if this is possible with OTEL library, because for now, attributes are provided during `startSpan` call...

**Comment by nioc** [comment]
It is possible with `span.setAttributes({ key: 'value' })`

**Comment by nioc** [comment]
This is strange, this attribute should be provided in the corresponding child span (parent is only a copy of first child, without custom attribute).

**Comment by sergimola** [comment]
I think the problem is reproduced only when the Node is the one initiating the trace like this one:
![image](https://github.com/user-attachments/assets/3c974a64-4d7b-4174-bbe3-a2eeb60cef50)

The ones I tried successfuly before were never the first node in the request.

**Comment by nioc** [comment]
Hello @sergimola I added the start/end select and merged the branch.

I try to reproduce your behavior with this flow:
![image](https://github.com/user-attachments/assets/445e3992-4226-4023-bba2-32188a3216e4)

<details>
<summary>Flow</summary>

``` json
[
    {
        "id": "39d8a10411d48939",
        "type": "tab",
        "label": "Flux 2",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "9ba1d899941be3a4",
        "type": "http in",
        "z": "39d8a10411d48939",
        "name": "",
        "url": "/test",
        "method": "get",
        "upload": false,
        "swaggerDoc": "",
        "x": 200,
        "y": 260,
        "wires": [
            [
                "ce8aab43247e7146",
                "3bbeaab9c0cb90ec"
            ]
        ]
    },
    {
        "id": "e281d03cc351b901",
        "type": "http response",
        "z": "39d8a10411d48939",
        "name": "",
        "statusCode": "",
        "headers": {},
        "x": 570,
        "y": 280,
        "wires": []
    },
    {
        "id": "8baa6949eea6e5e6",
        "type": "OpenTelemetry",
        "z": "39d8a10411d48939",
        "name": "",
        "url": "http://my-jaeger:4318/v1/traces",
        "serviceName": "Node-RED",
        "protocol": "http",
        "rootPrefix": "Message ",
        "timeout": 10,
        "ignoredTypes": "",
        "propagateHeadersTypes": "",
        "isLogging": true,
        "attributeMappings": [
            {
                "isAfter": false,
                "flow": "",
                "nodeType": "",
                "key": "aaa.test.attribute.t1",
                "path": "payload.param"
            },
            {
                "isAfter": true,
                "flow": "",
                "nodeType": "",
                "key": "aaa.test.attribute.t2",
                "path": "payload.param"
            }
        ],
        "x": 220,
        "y": 160,
        "wires": []
    },
    {
        "id": "5634f085108c0eaa",
        "type": "inject",
        "z": "39d8a10411d48939",
        "name": "",
        "props": [],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 210,
        "y": 360,
        "wires": [
            [
                "20e4e96290c4f477"
            ]
        ]
    },
    {
        "id": "20e4e96290c4f477",
        "type": "http request",
        "z": "39d8a10411d48939",
        "name": "",
        "method": "GET",
        "ret": "txt",
        "paytoqs": "ignore",
        "url": "http://localhost:1880/test?param=oldValue",
        "tls": "",
        "persist": false,
        "proxy": "",
        "insecureHTTPParser": false,
        "authType": "",
        "senderr": false,
        "headers": [],
        "x": 390,
        "y": 360,
        "wires": [
            [
                "f0026550fbd5aa6a"
            ]
        ]
    },
    {
        "id": "f0026550fbd5aa6a",
        "type": "debug",
        "z": "39d8a10411d48939",
        "name": "debug client",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 590,
        "y": 360,
        "wires": []
    },
    {
        "id": "ce8aab43247e7146",
        "type": "debug",
        "z": "39d8a10411d48939",
        "name": "debug server",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 390,
        "y": 240,
        "wires": []
    },
    {
        "id": "3bbeaab9c0cb90ec",
        "type": "function",
        "z": "39d8a10411d48939",
        "name": "transform",
        "func": "msg.payload.param = 'newValue'\nreturn msg;",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 380,
        "y": 280,
        "wires": [
            [
                "e281d03cc351b901"
            ]
        ]
    }
]
```
</details>

I find all spans for both client:
![image](https://github.com/user-attachments/assets/9b14040f-4959-4d4b-99d6-9db0ae14b831)

and server:
![image](https://github.com/user-attachments/assets/2ea7d06a-9b36-4bf1-822b-0351e98944d8)

But the first span does not have ending `aaa.test.attribute.t2` attribute set...

For now I propose to leave it as it is. Feel free to reopen a new issue if it is a real problem for you.

**Comment by sergimola** [comment]
Sadly I found a bug that will affect anyone not using span attributes.
It crashes there and spans are not created.

```
    at endSpan (/home/.node-red/dev/my-node/lib/opentelemetry-node.js:287:39)
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at /home/.node-red/dev/my-node/lib/opentelemetry-node.js:459:7
    at callNextHook (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:204:30)
    at invokeStack (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:237:5)
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:187:9)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:217:46
    at Node._complete (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:134:11)
    at /usr/src/node-red/node_modules/@node-red/nodes/core/network/21-httprequest.js:641:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by nioc** [comment]
I'll fix it tonight, thanks.

**Comment by sergimola** [comment]
In the meantime I've been trying to figure out what was wrong and I found the root cause.
If you use this flow you should be able to reproduce it.

![image](https://github.com/user-attachments/assets/ce7ab1cc-e564-4de3-925e-f6ebd5183788)

<details>
  <summary>Flow</summary>

```
[
    {
        "id": "b65fd34bda7d0828",
        "type": "inject",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "hello",
        "payloadType": "str",
        "x": 270,
        "y": 720,
        "wires": [
            [
                "4e22191e30c6d538"
            ]
        ]
    },
    {
        "id": "4e22191e30c6d538",
        "type": "http request",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "method": "POST",
        "ret": "txt",
        "paytoqs": "ignore",
        "url": "http://localhost:1880/hola",
        "tls": "",
        "persist": false,
        "proxy": "",
        "insecureHTTPParser": false,
        "authType": "",
        "senderr": false,
        "headers": [],
        "x": 470,
        "y": 720,
        "wires": [
            [
                "572adc6f502c7a12"
            ]
        ]
    },
    {
        "id": "619539eee9027a76",
        "type": "http in",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "url": "/hola",
        "method": "post",
        "upload": false,
        "swaggerDoc": "",
        "x": 460,
        "y": 780,
        "wires": [
            [
                "7ebf323a1a118135",
                "db4996cd4db9d5f0"
            ]
        ]
    },
    {
        "id": "572adc6f502c7a12",
        "type": "debug",
        "z": "f6f2187d.f17ca8",
        "name": "debug 2",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 640,
        "y": 720,
        "wires": []
    },
    {
        "id": "7ebf323a1a118135",
        "type": "http response",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "statusCode": "200",
        "headers": {},
        "x": 660,
        "y": 780,
        "wires": []
    },
    {
        "id": "db4996cd4db9d5f0",
        "type": "debug",
        "z": "f6f2187d.f17ca8",
        "name": "debug 3",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 700,
        "y": 900,
        "wires": []
    }
]
```
</details>

I added some logs and as you can see, the child span in the second request (the one starting with `Message http in`) is not ended, but it's the parent that is ended. As the custom attributes are set only in the child, then that's why they don't show up in Jaeger.

![image](https://github.com/user-attachments/assets/1fca5004-fe18-4cf5-ba53-26324ab8905f)
![image](https://github.com/user-attachments/assets/0d2aade4-af06-45d5-a3b5-8559346b3cca)

This is how my OTEL node is configured:
![image](https://github.com/user-attachments/assets/faed2796-a76c-412d-ac7a-159f5d55f33a)

**Comment by nioc** [comment]
I'm not sure, what is the problem here.
I reproduced your flow with this OTEL configuration:

``` json
[
    {
        "id": "8f8a1ebd7c7cffeb",
        "type": "OpenTelemetry",
        "z": "21b65ab6970c08e5",
        "name": "",
        "url": "http://my-otel-collector:4318/v1/traces",
        "serviceName": "Node-RED",
        "protocol": "http",
        "rootPrefix": "Message ",
        "timeout": 10,
        "ignoredTypes": "debug",
        "propagateHeadersTypes": "",
        "isLogging": true,
        "attributeMappings": [
            {
                "isAfter": false,
                "flow": "",
                "nodeType": "http in",
                "key": "bbb",
                "path": "payload"
            }
        ],
        "x": 480,
        "y": 140,
        "wires": []
    }
]
```
And with these, I have the following 3 spans:
- parent (`http in`),
- `http in` (which has the expected `bbb` attribute as it is in parsed during node processing start),
- and `http response`

![image](https://github.com/user-attachments/assets/50248a73-a672-4b94-b06c-6d6cd3087a8b)

If we look closer (sorry for the ugly picture 😉):
![image](https://github.com/user-attachments/assets/a685f969-e149-487b-89f0-e17e9f6d5390)

All span are ended.
But I had to wrote a specific `http in`/`http response` process [here](https://github.com/nioc/node-red-contrib-opentelemetry/blob/master/lib/opentelemetry-node.js#L303-L315) which ends the `http in` child span when ending `http response` span, this is because `http in` nodes does not emit an `onComplete` event. That's why we can not have an "after-node-process" parsing of span attribute on `http in` node (but I do not think is should be useful...).  

If the problem you're talking is about the lack of attribute in parent, this is by design: as parent is also the first child, I prefer avoiding duplicate data.

Otherwise, could you post a screenshot about the span which had a problem?

**Comment by sergimola** [comment]
Now I fully understand what's the expected outcome.
The problem is not that the root (parent) span doesn't have the attributes.
The problem is that there is a whole missing span.

If you look at my screenshot, the `http in` span is completely missing (that's expected in my case considered the `http in` span is not being ended as seen in my logs)
![image](https://github.com/user-attachments/assets/ff954bb8-614e-448a-bb2b-2f74823c349e)

**Comment by sergimola** [comment]
> Now I fully understand what's the expected outcome. The problem is not that the root (parent) span doesn't have the attributes. The problem is that there is a whole missing span.
> 
> If you look at my screenshot, the `http in` span is completely missing (that's expected in my case considered the `http in` span is not being ended as seen in my logs) ![image](https://private-user-images.githubusercontent.com/16050368/402325052-ff954bb8-614e-448a-bb2b-2f74823c349e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2NzM5NzksIm5iZiI6MTczNjY3MzY3OSwicGF0aCI6Ii8xNjA1MDM2OC80MDIzMjUwNTItZmY5NTRiYjgtNjE0ZS00NDhhLWJiMmItMmY3NDgyM2MzNDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEyVDA5MjExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYWUwM2MzNDk1ZGY2YWQ1NzM0NjA5YTI4YjM0ZjFiZDc3ODc2ODE5NDJhMzJiMGNiODMyNWQxOWIwOWI3YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5FzKrfz64v3e2RCvlBPPP-yuvwRbwSyABn86th5jt3I)

I deleted everything and started from scratch in a playground environment and now I also have the `http in` span that was missing for me before.

![image](https://github.com/user-attachments/assets/6e58830e-3795-40ae-9268-9a7fdce7502f)

For `http in` it works fine because there is some explicit code to handle it, but what I am seeing is that "input" nodes don't trigger the `onComplete`. 
I was testing this with `server-events` from `node-red-contrib-home-assistant-websocket`, but the problem is also valid for `tcp in` for instance.

Check it out with this flow:
<details>
<summary>Flow</summary>

```
[
    {
        "id": "f902e7ec780ac4b2",
        "type": "tcp out",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "host": "localhost",
        "port": "1234",
        "beserver": "client",
        "base64": false,
        "end": false,
        "tls": "",
        "x": 890,
        "y": 540,
        "wires": []
    },
    {
        "id": "4328fd4852f0f2cd",
        "type": "tcp in",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "server": "server",
        "host": "",
        "port": "1234",
        "datamode": "stream",
        "datatype": "utf8",
        "newline": "",
        "topic": "",
        "trim": false,
        "base64": false,
        "tls": "",
        "x": 680,
        "y": 580,
        "wires": [
            [
                "50bcbab4f2f435c3"
            ]
        ]
    },
    {
        "id": "50bcbab4f2f435c3",
        "type": "debug",
        "z": "f6f2187d.f17ca8",
        "name": "debug 1",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 860,
        "y": 580,
        "wires": []
    },
    {
        "id": "65a08a2318bc4ca3",
        "type": "inject",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "hello",
        "payloadType": "str",
        "x": 690,
        "y": 540,
        "wires": [
            [
                "f902e7ec780ac4b2"
            ]
        ]
    }
]
```

</details>

You'll get this: (only the parent span, not the child span)
![image](https://github.com/user-attachments/assets/0298c6f3-0f71-48d6-adcf-3992143f4e6e)

**Comment by nioc** [comment]
Thanks for the detailed explanation.

Can you copy your last comment as a new issue? I can't assure you I will find a fix, but at least we should keep track of it it.
